### ISSUE TITLE
crash on start fallied because cant find exe but I chose F as location

### ISSUE THREAD

**Issue by Tansimmo2** [overkillwtf/folon-steamdeck-installer#10]
I get this error when launching. If i launch from steam it justc rashes so I tried to launch from the GOG launcher. I followed the steps from this website https://overkill.wtf/fallout-london-steam-deck-1-click-installer/ 
![20240812_030739](https://github.com/user-attachments/assets/1dfdbfdd-3465-490a-a508-41da870400d7)

**Comment by krupar101** [comment]
The script is still running at this point.

The correct step after the installation is completed in the installer is to close the installer. 

After you close it the script performs further steps.

**Comment by Tansimmo2** [comment]
I am going through the update now and will close everything. I did do this already and launched fallout 4 from steam but it just crashes right away. Thats why I tried launching from the launcher in desktop mode and I get that error. Sorry if im being confusing

**Comment by krupar101** [comment]
The update process should fix this as well. let us know how it went :)

**Comment by Tansimmo2** [comment]
updating it fixed it. Ty for ther help sorry if was a bother. You guys are amazing for making this auto installer

**Comment by krupar101** [comment]
Great to hear this!
Closing the issue with the resolution:
If Fallout 4 crashes after first installation via the script -> run the update process in the script one more time to ensure all the steps were completed successfully. 
Make sure you close the GoG installer as soon as it is done installing the update.
