### ISSUE TITLE
Unhandled exception "EXCEPTION_INT_DIVIDE_BY_ZERO" at 0x000141D1777B Fallout.exe+1D1777B

### ISSUE THREAD

**Issue by RemusRorschach** [overkillwtf/folon-steamdeck-installer#11]
I followed this letter for letter and immediately crash. Here is my crash log error note:

Unhandled exception "EXCEPTION_INT_DIVIDE_BY_ZERO" at 0x000141D1777B Fallout.exe+1D1777B

Please help!!

**Comment by krupar101** [comment]
This is a known issue if you haven't ran the script till the end. 

After the GoG Installer finishes you need to close it -> The script continues with the setup. 

Try to run the script one more time and select: 
'Continue from last known step' if this option shows up

or 
'Update' and go through the whole update process once.

**Comment by RemusRorschach** [comment]
I definitely ran it until it told me I could close it the first time.  But running it again and doing the update process seemed to do the trick.  Thank you!

**Comment by krupar101** [comment]
Awesome, closing the issue.
Solution:
Run the update process if the game shows an error after the first install.
