### ISSUE TITLE
Installer do not work when you have the game through family share

### ISSUE THREAD

**Issue by Jaksan** [overkillwtf/folon-steamdeck-installer#13]
Installer stops working once you log into the steam part as it fails to find the depots for the game and DLCs even if you have them installed but through family share. Maybe this is intended behavior. Otherwise an option to stop the depot check would solve it if possible I imagine

**Comment by krupar101** [comment]
This is not an issue of the script. The depot download is necessary to downgrade the game. You can only download depots on the account that owns Fallout 4 and all the DLC's. So to put it shortly it's a Steam limitation. 

However - If you downgrade the game another way you can run the 'Update' Process to automate the installation.

You can get the official linux downgrader from here: 
https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/download/1.5.1/FOLON-Downgrader-Linux.zip

To run the downgrader you need to first unzip it and then have the folder where it's unzipped opened in the File Explorer (dolphin).

Right-click on the file -> Properties -> Permissions -> select "make executable".

open the location of the unzipped file in the Konsole (Terminal). You should be able to do it with a right click inside the folder -> then select "Open Terminal Here"

to run it just write in the Terminal: ./FOLON-Downgrader

Unfortunately I think it will also not work if you don't have the game purchased with all DLC's.


So the resolution for you:
1. You can try to get the account login for the family member who has the game purchased. 
2. You can buy the game on your account. Currently it's 60% off on Steam. https://store.steampowered.com/sub/199943/
