### ISSUE TITLE
Unable to Reach the Fallout London Title Screen

### ISSUE THREAD

**Issue by parhelic** [overkillwtf/folon-steamdeck-installer#14]
I was following your helpful 'fallout-london-steam-deck-1-click-installer' guide successfully until I reached step 7 where I kept receiving the message that it was unable to continue because Proton Experimental was not in my library and needed to be added. This was confusing to me because Proton Experimental is actually there.  

After many hours of struggling, I then installed Protontricks and was able to navigate to and execute the Fallout London installer.exe. Via Protontricks, I selected Fallout 4 and installed the Fallout London files into the correct Fallout 4 folder location at Z:/home/deck/steam/steamapps/common/Fallout4

I attempted to continue your script afterwards but encountered the same message regarding Proton Experimental needing to be in my library.

Today I tried running the alternative command you provided in a response comment today.

curl -s https://raw.githubusercontent.com/overkillwtf/folon-steamdeck-installer/main/fallout.sh 

This script completed successfully with the following message - "All steps completed successfully! You can now close the terminal / Konsole. Fallout London can be launched from Fallout 4 Steam page"

However, when trying to launch Fallout London, I can reach the initial Fallout menu screen which allows me to select Play, Options etc. but when I click Play, the intro only plays for a few seconds before aborting at the "Protect and survive" animated message. It doesn't reach the Fallout London title screen  - I'm sent back to the Fallout 4 game selection screen in Steam. 

Do you have some suggestions I can try? Any log files I should attach (where o access?)? I am launching the game with Proton Experimental enabled.

**Comment by krupar101** [comment]
Sure, let's solve that :) 

First of all - You can probably easily fix this by moving Proton Experimental from the microSD card to your SSD. This can be done through Steam as Proton Experimental is already added in your games library. 

The second issue is most likely related with the fact that the script does not recognize your microSD mount location. 

Please go to the Desktop mode -> open file explorer (dolphin) -> Go to the following directory in your rood:

"/run/media"  -> provide a screenshot of what you see there.
"run/media/deck" -> provide a screenshot of what you see there.

**Comment by parhelic** [comment]
Brilliant! Thanks so much for your help on this :-)

User error was involved since I had forgotten that I had previously moved my Proton Experimental to my SD card when I was trying to make space on the internal storage. 

I moved Proton Experimental back to my internal drive and then ran the script successfully.

There are 2 questions I'm hoping you can answer:

1. I mistakenly opted to not disable auto-updates to Fallout 4. I would like to disable them to avoid the risk of a future auto update breaking change. Do you have a script I could run to achieve this please?
2. If later I wanted to move my Fallout London installation to my SD card, is this a simple, straightforward task? 

> Sure, let's solve that :)
> 
> First of all - You can probably easily fix this by moving Proton Experimental from the microSD card to your SSD. This can be done through Steam as Proton Experimental is already added in your games library.
> 
> After you do that run the script using this command from overkill website: curl -O https://raw.githubusercontent.com/overkillwtf/folon-steamdeck-installer/main/fallout.sh && chmod +x fallout.sh && ./fallout.sh
> 
> Second of all issue is most likely related with the fact that the script does not recognize your microSD mount location.
> 
> Please go to the Desktop mode -> open file explorer (dolphin) -> Go to the following directory in your root:
> 
> "/run/media" -> provide a screenshot of what you see there. "run/media/deck" -> provide a screenshot of what you see there.

**Comment by krupar101** [comment]
Examples of screenshots:
![image](https://github.com/user-attachments/assets/d95e25a5-e9e9-41bf-9598-2110a4c7c148)

![image](https://github.com/user-attachments/assets/87fa9a0b-fe17-44cc-b094-94af71c280dc)

**Comment by parhelic** [comment]
Hi here are the screenshots you requested

![deck](https://github.com/user-attachments/assets/b2048f23-f6b7-4e98-86e4-1b772b2b7cb9)
![media](https://github.com/user-attachments/assets/18019854-69ef-49b2-9dd4-ff2b3f94bb2e)

Thanks for the information regarding disabling the updates, I'll give it a try.

**Comment by krupar101** [comment]
Thank you. We are working on improving the script to recognize the mount location automatically. Additionally the next version will likely include GoG Fallout 4 version installation through heroic :)
