### ISSUE TITLE
I’m a dumbass

### ISSUE THREAD

**Issue by Emphaticsqueak** [overkillwtf/folon-steamdeck-installer#15]
Hey folks I’m a dumbass and accidentally didn’t select the option to disable auto updates when I ran the script, how can I re-run this element of it?

**Comment by krupar101** [comment]
That is a simple question that could have a complex or an easy answer. 

The easiest way to try first:

1. run this command in konsole: 
echo "17" > "$HOME/.folon_patch_progress"

2. run the script again using this command: 
curl -O https://raw.githubusercontent.com/overkillwtf/folon-steamdeck-installer/main/fallout.sh && chmod +x fallout.sh && ./fallout.sh

3. When this window appears click "Continue from last known step"

![image](https://github.com/user-attachments/assets/ba6cba45-a784-4b2b-8595-3d71500fa503)

**Comment by krupar101** [comment]
Solution provided. In case of any new problem please open a new GitHub issue.
