### ISSUE TITLE
Error after install 

### ISSUE THREAD

**Issue by Dfreeear** [overkillwtf/folon-steamdeck-installer#17]
Im getting this error 'failed to start game: fork/exec H:\f4se_loader.exe: Directory name invalid

Im not sure if i need to change the path in a script running.

I installed it in H drive but that doesnt reflect the true path in the file system

Its /games/heroic/fallout4.../f4se_loader.exe

**Comment by krupar101** [comment]
The script should be run till the end. Once the GoG Installer is finished you need to close it and let the script run until you get the message that the game is ready to run.

If you got this message it's also possible that you are launching it from Heroic Launcher from Fallout London shortcut. 
This will not work. 

You need to run it from Fallout 4 page on Steam. f4se_loader is renamed purposefully to fallout4launcher to make the game run automatically with the correct launcher from the official game page.

**Comment by Dfreeear** [comment]
Thanks for getting back to me! I did run the script until the end and ran it through fallout 4 on game mode. I tried a few different attempts changing the proton version, running in heroic, finally i tried direct through kontrol and that thats when that error emerged. Previous attempts just crashed with no error message.

I will try re-run the script from the start, does it need any prep before re running or will all files be auto replaced? Many thanks for looking over this

**Comment by krupar101** [comment]
Let me know how it went. In case of any issues make sure to leave a comment.

**Comment by Schnulliboss** [comment]
Hello :) I own the GOG Version and i get the same error. but i dont know how to start it exept with the heroic launcher. (sorry for possiple writting errors)

**Comment by krupar101** [comment]
No worries,
Are you launching Fallout 4 or Fallout London from Heroic?

You should be launching Fallout 4 - make sure to run it with proton experimental.

Also - do not add it as a non steam game manually - this will not work. Use the Add to steam Heroic functionality.

**Comment by krupar101** [comment]
> Hello :) I own the GOG Version and i get the same error. but i dont know how to start it exept with the heroic launcher. (sorry for possiple writting errors)

No worries,
Are you launching Fallout 4 or Fallout London from Heroic?

You should be launching Fallout 4 - make sure to run it with proton experimental.

Also - do not add it as a non steam game manually - this will not work. Use the Add to steam Heroic functionality.

**Comment by krupar101** [comment]
![image](https://github.com/user-attachments/assets/ff19f0db-1023-44e3-9413-93566e412239)

![image](https://github.com/user-attachments/assets/24c3b2dd-fd5c-4e18-a911-2b2bcb847f2e)

**Comment by Schnulliboss** [comment]
aah i did that :/ okay great! thanks i will try this and let you know! thank you!

**Comment by Schnulliboss** [comment]
sadly! it still doesn work :/ still the sam issue. i used proton experimental and started it from the heroic launcher. i added a photo of error
![Screenshot_20240827_182806_Gallery](https://github.com/user-attachments/assets/e1960754-a554-48e3-acc5-0a828cd4a984)

**Comment by krupar101** [comment]
> Finalie it worked :D thanks for your great script and your help! Awesome!

Great to hear that!
Have fun and mind the gap!

**Comment by Schnulliboss** [comment]
one last question: how can i change the graphic setings? the menue ist opening anymore while starting fallout 4.

**Comment by krupar101** [comment]
The best way is to do this: 

1. Find your Fallout 4 installation Directory and open it in file explorer.
2. In that directory you will see those 2 files: fallout4launcher.exe and fallout4launcher.exe.old
3. Rename the fallout4launcher.exe to fallout4launcher.exe.f4se
4. Rename fallout4launcher.exe.old to fallout4launcher.exe
5. Run the game - launcher should open -> change the settings there.

Then to make fallout london work again:

Rename the fallout4launcher.exe to fallout4launcher.exe.old
Rename fallout4launcher.exe.f4se to fallout4launcher.exe

The default installation Path for Heroic launcher is: 
/Games/Heroic/Fallout 4 Game of the Year

**Comment by krupar101** [comment]
Issue closed after 3 weeks with no response.
