### ISSUE TITLE
Error on Install Step 7

### ISSUE THREAD

**Issue by digidude512** [overkillwtf/folon-steamdeck-installer#2]
On Step 7 after selecting Drive F I just get

"Application encountered an error during this operation [ cannot read list: unable to get source directory: readdir Z:\home\Games\Heroic\Fallout London: Invalid function. ].

**Comment by krupar101** [comment]
Can you please share the whole output that you get in Konsole?
Also, is this error appearing in GoG installer or the Konsole?

**Comment by digidude512** [comment]
> Can you please share the whole output that you get in Konsole? Also, is this error appearing in GoG installer or the Konsole?
> 
> It would be great if you could also share a screenshot of this.

curl -O https://raw.githubusercontent.com/overkillwtf/folon-steamdeck-installer/main/fallout.sh && chmod +x fallout.sh && ./fallout.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41570  100 41570    0     0   172k      0 --:--:-- --:--:-- --:--:--  172k
Fallout 4 recognized to be installed on Internal SSD
Continue from last known step.
Step 7: Manual Installation of Fallout London
Proton Experimental is installed on Internal SSD. Continue...
Fallout London installation path found.
Drive F: successfully created pointing to /home/deck/.steam/steam/steamapps/common/Fallout 4


GoG installer for Fallout London will now launch.

1. Click Install
2. Select Drive F:
3. Click Install Here

Close the installer after it's done to continue the setup process.

wineserver: no process found
wine: using kernel write watches, use_kernel_writewatch 2.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
Correct. Game does not launch with standard launcher
You are using a downgraded standard Fallout 4 launcher exe.
ERROR: Fallout London is not installed or installation was not successful.
ERROR: Please run the script again and select 'Continue from last known step'
(1)(deck@steamdeck ~)$ 

![image](https://github.com/user-attachments/assets/8f435d35-fd1a-48b0-85bc-d3a77ae990fe)

![image](https://github.com/user-attachments/assets/d42e7e17-f770-4e64-9d5b-a7936271fe51)

**Comment by krupar101** [comment]
1. Do you have any external drives connected to the steam deck other than the internal SSD and microSD card? 
2. Where is Proton - Experimental installed (If it's on microSD card try to reinstall it on the SSD. 
3. Have you tried reinstalling Fallout London from Heroic?

**Comment by digidude512** [comment]
> 1. Do you have any external drives connected to the steam deck other than the internal SSD and microSD card?
> 
>     2. Where is Proton - Experimental installed (If it's on microSD card try to reinstall it on the SSD.
> 
>     3. Have you tried reinstalling Fallout London from Heroic?

1: No Externals, Only SSD and microSD
2: Proton only on SSD ever
3: I've tried completely reinstalling Fallout 4, Fallout London, Heroic and starting as fresh as I can.

**Comment by krupar101** [comment]
Please try to run this command in Konsole:
ln -s "/" "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"

Then run the script one more time -> 'Continue from the last known step".

**Comment by digidude512** [comment]
ln: failed to create symbolic link '/home/deck/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:/': No such file or directory

**Comment by krupar101** [comment]
In this case run this first:
mkdir -p "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices"

then:
ln -s "/" "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"

then rerun the script :)

**Comment by digidude512** [comment]
(deck@steamdeck ~)$  ln -s "/" "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"
ln: failed to create symbolic link '/home/deck/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:/': No such file or directory
(1)(deck@steamdeck ~)$

**Comment by krupar101** [comment]
Can you also provide what you see under the F: folder in the meantime?

**Comment by digidude512** [comment]
![image](https://github.com/user-attachments/assets/1e2a9acc-b142-4394-9be7-fd121aea45e1)

**Comment by krupar101** [comment]
Ok then. Let's try one more thing.
Run this:
rm -f "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"

Then this:
ln -s "/" "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"

Then re-run the script

**Comment by digidude512** [comment]
Still no change

![356393547-d42e7e17-f770-4e64-9d5b-a7936271fe51](https://github.com/user-attachments/assets/4e5e1a09-0095-46ad-bfb4-1c6e0ca32b36)

**Comment by krupar101** [comment]
Do you have a mucroSD card in your steam deck? 

You can try to uninstall Fallout London from Heroic -> Install Fallout London in heroic again on the microSD card. (You will need to change the default install path. On the window where you select the directory SD card can be found on the bottom of the left side of the window.)

Then try to run the script one more time. 

Looks like proton does not have access to your home directory.  Not sure why that could be.

**Comment by FitzWM** [comment]
I'm getting exactly this issue when trying to install on an Arch system (not a Steam Deck). Obviously, mine isn't the intended environment. Still, it's really weird that FOL's installer is the only game or mod (or EXE, really) I've ever installed via Wine or Proton, manually or through one app or other, that didn't have full access to the same folders as my user on the Z: drive.

It's not just this script, either. It happens however I run the FOL installer, whether via Heroic, Lutris, Steam, Dolphin, or the terminal. The really weird thing is that it gets access to seemingly random sets of directories, depending on how I run it. If I run it from Steam, it can see etc, run, and var. If I run it from Dolphin or in the terminal with a WINEPREFIX, it can see a lot more, but never home. I guess the difference is from the installer thinking it's under steamuser or my actual user? I tried making a symbolic link to my games directory in opt, since the installer could see that, but it looks like it can't see symlinks, and I'm reluctant to create a hardlink just for this. I suppose I could try copying the FO4 install to one of the directories it can see and then copying it back. Maybe that would work?

I'm not sure what to try next, honestly. I've literally never seen this behavior before, and I've probably installed around 200 games, old and new, and a lot more mods and external programs since moving fully to Linux this year. I'm pretty familiar with the various processes at this point, so I'm happy to test things if it'll help. I'd love to try this mod out, but now that I've finally cut the cord, I'm extremely reluctant to remake my Windows partition for anything short of a national emergency.

**Comment by digidude512** [comment]
> Do you have a microSD card in your steam deck?
> 
> You can try to uninstall Fallout London from Heroic -> Install Fallout London in heroic again on the microSD card. (You will need to change the default install path. On the window where you select the directory SD card can be found on the bottom of the left side of the window.)
> 
> Then try to run the script one more time.
> 
> Looks like proton does not have access to your home directory. Not sure why that could be.

IT FINALLY INSTALLED!

I had some visual problems with the tube at character creation but the mod is finally running!

Thank you!

**Comment by krupar101** [comment]
> I'm getting exactly this issue when trying to install on an Arch system (not a Steam Deck). Obviously, mine isn't the intended environment, but I was getting similar access errors with other methods, so I thought I'd try this script. Unfortunately, I've hit the same wall here. The FOL installer is the only game or mod (or EXE, really) I've ever installed via Wine or Proton, manually or through one app or other, that didn't have full access to the same folders as my user on the Z: drive.
> 
> It's not just this script, either. It happens however I run the FOL installer, whether via Heroic, Lutris, Steam, Dolphin, or the terminal. The really weird thing is that it gets access to different sets of directories, depending on how I run it. If I run it from Steam, it can see etc, run, and var. If I run it from Dolphin or in the terminal with a WINEPREFIX, it can see a lot more, but never home. I guess the difference is from the installer thinking it's under steamuser or my actual user? I tried making a symbolic link to my games directory in opt, since the installer could see that, but it looks like it can't see symlinks, and I'm reluctant to create a hardlink just for this. I also had FOL installed via the AUR version of Heroic at first, so I tried uninstalling that and reinstalling it via the Flatpak version, but no dice. I suppose I could try copying the FO4 install to one of the directories it can see and then copying it back. Maybe that would work?
> 
> I'm not sure what to try next, honestly. I've literally never seen this behavior before, and I've probably installed around 200 games, old and new, and a lot more mods and external programs since moving fully to Linux last year. I'm pretty familiar with the various processes at this point, so I'm happy to test things if it'll help. I'd love to try this mod out, but now that I've finally cut the cord, I'm extremely reluctant to remake my Windows partition for anything short of a national emergency.

I will play around with settings to check what could cause this. Will update this over the weekend. Maybe creating the z: symlink while the app is running would work?

**Comment by krupar101** [comment]
> I'm getting exactly this issue when trying to install on an Arch system (not a Steam Deck). Obviously, mine isn't the intended environment, but I was getting similar access errors with other methods, so I thought I'd try this script. Unfortunately, I've hit the same wall here. The FOL installer is the only game or mod (or EXE, really) I've ever installed via Wine or Proton, manually or through one app or other, that didn't have full access to the same folders as my user on the Z: drive.
> 
> It's not just this script, either. It happens however I run the FOL installer, whether via Heroic, Lutris, Steam, Dolphin, or the terminal. The really weird thing is that it gets access to different sets of directories, depending on how I run it. If I run it from Steam, it can see etc, run, and var. If I run it from Dolphin or in the terminal with a WINEPREFIX, it can see a lot more, but never home. I guess the difference is from the installer thinking it's under steamuser or my actual user? I tried making a symbolic link to my games directory in opt, since the installer could see that, but it looks like it can't see symlinks, and I'm reluctant to create a hardlink just for this. I also had FOL installed via the AUR version of Heroic at first, so I tried uninstalling that and reinstalling it via the Flatpak version, but no dice. I suppose I could try copying the FO4 install to one of the directories it can see and then copying it back. Maybe that would work?
> 
> I'm not sure what to try next, honestly. I've literally never seen this behavior before, and I've probably installed around 200 games, old and new, and a lot more mods and external programs since moving fully to Linux last year. I'm pretty familiar with the various processes at this point, so I'm happy to test things if it'll help. I'd love to try this mod out, but now that I've finally cut the cord, I'm extremely reluctant to remake my Windows partition for anything short of a national emergency.

Potential solution:

1. Run the script one more time
2. Click on "Install" or "Change location" depending on what you see here:
![image](https://github.com/user-attachments/assets/3bb2507f-d684-4eef-9a0a-179526aa3f8b)
3. While on this screen open a new konsole window:
![image](https://github.com/user-attachments/assets/75b5d5d1-056c-4b4d-b178-b8b4ee3f1c21)
4. Type in the following commands to recreate the symlink: 

rm -f "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"
ln -s "/" "$HOME/.steam/steam/steamapps/compatdata/377160/pfx/dosdevices/z:"

5. Select Drive F:
6. Try to install.

**Comment by zee5679** [comment]
Can report try everything suggested here and no dice. I am also getting this issue

**Comment by krupar101** [comment]
Ok, here is a workaround:

1. Open Heroic Launcher 
2. Go to Fallout London's Page
3. Click the button with the 'sliders' icon. 
4. Change the game to run with proton experimental
5. scroll down in this window
6. open WINECFG (If it doesn't open install wine from discover store)
7. go to Drives tab.
8. Add a new drive pointing to Fallout 4 directory.
For steam deck the paths are as follows

SSD Installation:
/home/deck/.steam/steam/steamapps/common/Fallout 4

SD card installation:
/run/media/mmcblk0p1/steamapps/common/Fallout 4

9. Confirm the action
10. Launch Fallout London from heroic manually and proceed to install
11. You will see your added drive in the installer. Select it.
12. Proceed with the installation
13. After that is done run the script again -> Continue from last step
14. As soon as the GoG window appears close it -> The script will continue.

**Comment by FitzWM** [comment]
Alright, I've tried both the workarounds posted above, but unfortunately, both give me the same error: "cannot read list: unable to get source directory: readdir Z:\home\<redacted>\Games\Heroic\Fallout London: Invalid function". I also tried installing manually, but the method I used to use to get MO2 working on Linux no longer works because some random Python dependency for it is apparently now abandonware ;_;

**Comment by krupar101** [comment]
> Alright, I've tried both the workarounds posted above, but unfortunately, both give me the same error: `cannot read list: unable to get source directory: readdir Z:\home\<redacted>\Games\Heroic\Fallout London: Invalid function`. I also tried installing manually, but the method I used to use to get MO2 working on Linux no longer works because some random Python dependency for it is apparently now abandonware ;_;
> 
> I did try meddling with Flatseal settings and using the non-Flatpak version of Heroic, but no dice with either method.

This is very interesting. Have you tried to go to Heroic Launcher's wine manager and installing proton ge? 
![image](https://github.com/user-attachments/assets/625dbe8a-c0c7-4ca1-8374-b712a2ba409a)

From my experience 9-10 works quite well. 

Please also make sure to run the game with this proton version:
![image](https://github.com/user-attachments/assets/4f9a5395-ccaa-465a-b1f4-b2051a11d209)

**Comment by krupar101** [comment]
Issue closed after 3 weeks with no response.
