### ISSUE TITLE
When hard drive is plugged in to steam deck F:/ Drive can not be selected as it does not contain valid Fallout 4

### ISSUE THREAD

**Issue by minimanlion** [overkillwtf/folon-steamdeck-installer#3]
I have also tried removing the hard drive and selecting drive F:/ but it will not let me. See full konsole log below:

(1)(deck@steamdeck ~)$ curl -O https://raw.githubusercontent.com/overkillwtf/folon-steamdeck-installer/main/fallout.sh && chmod +x fallout.sh && ./fallout.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41570  100 41570    0     0   121k      0 --:--:-- --:--:-- --:--:--  122k
Fallout 4 recognized to be installed on SD Card
Heroic Launcher is installed.
Setting up downgrade-list...
SD Card detected
microSD Card Selected
Setting up SteamCMD...
steamcmd.sh
linux32/steamcmd
linux32/steamerrorreporter
linux32/libstdc++.so.6
linux32/crashhandler.so
STEAMCMD_DIR is set to /run/media/mmcblk0p1/Downloads/SteamCMD
Please enter your Steam login credentials.
Note: Your login details are secure and will NOT be stored.
Running SteamCMD with provided credentials...
Redirecting stderr to '/home/deck/.local/share/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 58,902 KB)...
[  0%] Downloading update (0 of 58,902 KB)...
[  0%] Downloading update (0 of 58,902 KB)...
[  0%] Downloading update (1,804 of 58,902 KB)...
[  3%] Downloading update (4,407 of 58,902 KB)...
[  7%] Downloading update (7,101 of 58,902 KB)...
[ 12%] Downloading update (9,064 of 58,902 KB)...
[ 15%] Downloading update (10,985 of 58,902 KB)...
[ 18%] Downloading update (12,958 of 58,902 KB)...
[ 22%] Downloading update (15,130 of 58,902 KB)...
[ 25%] Downloading update (17,048 of 58,902 KB)...
[ 28%] Downloading update (18,929 of 58,902 KB)...
[ 32%] Downloading update (21,074 of 58,902 KB)...
[ 35%] Downloading update (23,032 of 58,902 KB)...
[ 39%] Downloading update (24,928 of 58,902 KB)...
[ 42%] Downloading update (26,900 of 58,902 KB)...
[ 45%] Downloading update (29,116 of 58,902 KB)...
[ 49%] Downloading update (31,110 of 58,902 KB)...
[ 52%] Downloading update (33,056 of 58,902 KB)...
[ 56%] Downloading update (34,924 of 58,902 KB)...
[ 59%] Downloading update (37,165 of 58,902 KB)...
[ 63%] Downloading update (39,108 of 58,902 KB)...
[ 66%] Downloading update (40,872 of 58,902 KB)...
[ 69%] Downloading update (42,366 of 58,902 KB)...
[ 71%] Downloading update (43,343 of 58,902 KB)...
[ 73%] Downloading update (44,308 of 58,902 KB)...
[ 75%] Downloading update (45,287 of 58,902 KB)...
[ 76%] Downloading update (46,328 of 58,902 KB)...
[ 78%] Downloading update (47,318 of 58,902 KB)...
[ 80%] Downloading update (48,303 of 58,902 KB)...
[ 82%] Downloading update (49,319 of 58,902 KB)...
[ 83%] Downloading update (50,327 of 58,902 KB)...
[ 85%] Downloading update (51,337 of 58,902 KB)...
[ 87%] Downloading update (52,405 of 58,902 KB)...
[ 88%] Downloading update (53,379 of 58,902 KB)...
[ 90%] Downloading update (54,395 of 58,902 KB)...
[ 92%] Downloading update (55,521 of 58,902 KB)...
[ 94%] Downloading update (56,542 of 58,902 KB)...
[ 95%] Downloading update (57,485 of 58,902 KB)...
[ 97%] Downloading update (58,535 of 58,902 KB)...
[ 99%] Downloading update (58,902 of 58,902 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/home/deck/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/deck/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
UpdateUI: skip show logosteamcmd.sh[80467]: Restarting steamcmd by request...
Redirecting stderr to '/home/deck/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/deck/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'minimanlion' to Steam Public...
Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code: [REDACTED]
OK
Waiting for client config...OK
Waiting for user info...OK
download_depot 377160 377161 7497069378349273908
Downloading depot 377161 (5332 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_377161" (12 files, manifest 7497069378349273908) 
download_depot 377160 377162 5847529232406005096
Downloading depot 377162 (48 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_377162" (1 files, manifest 5847529232406005096) 
download_depot 377160 377163 5819088023757897745
Downloading depot 377163 (18022 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_377163" (65 files, manifest 5819088023757897745) 
download_depot 377160 377164 2178106366609958945
Downloading depot 377164 (3243 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_377164" (7 files, manifest 2178106366609958945) 
download_depot 377160 435880 1255562923187931216
Downloading depot 435880 (54 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_435880" (5 files, manifest 1255562923187931216) 
download_depot 377160 435870 1691678129192680960
Downloading depot 435870 (365 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_435870" (4 files, manifest 1691678129192680960) 
download_depot 377160 435871 5106118861901111234
Downloading depot 435871 (109 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_435871" (2 files, manifest 5106118861901111234) 
download_depot 377160 435881 1207717296920736193
Downloading depot 435881 (1882 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_435881" (4 files, manifest 1207717296920736193) 
download_depot 377160 435882 8482181819175811242
Downloading depot 435882 (474 MB) ... 
Depot download complete : "/run/media/mmcblk0p1/Downloads/SteamCMD/linux32\steamapps\content\app_377160\depot_435882" (2 files, manifest 8482181819175811242) 
download_depot 480630 5527412439359349504
Depot download failed : missing app info for 480630
download_depot 480631 6588493486198824788
Depot download failed : missing app info for 480631
download_depot 393885 5000262035721758737
Depot download failed : missing app info for 393885
download_depot 490650 4873048792354485093
Depot download failed : missing app info for 490650
download_depot 393895 7677765994120765493
Depot download failed : missing app info for 393895
quit
All files downloaded successfully.
STEAMCMD_DIR is set to /run/media/mmcblk0p1/Downloads/SteamCMD
Moving downloaded content and cleaning up...
sending incremental file list
./
Fallout4.ccc
Fallout4.exe
Fallout4Launcher.exe
Fallout4_Default.ini
GFSDK_GodraysLib.x64.dll
GFSDK_SSAO_D3D11.win64.dll
High.ini
Low.ini
Medium.ini
Ultra.ini
bink2w64.dll
cudart64_75.dll
flexExtRelease_x64.dll
flexRelease_x64.dll
installscript.vdf
msvcp110.dll
msvcr110.dll
nvToolsExt64_1.dll
nvdebris.txt
steam_api64.dll
Data/
Data/DLCCoast - Geometry.csg
Data/DLCCoast - Main.ba2
Data/DLCCoast - Textures.ba2
Data/DLCCoast - Voices_en.ba2
Data/DLCCoast.cdx
Data/DLCCoast.esm
Data/DLCRobot - Geometry.csg
Data/DLCRobot - Main.ba2
Data/DLCRobot - Textures.ba2
Data/DLCRobot - Voices_en.ba2
Data/DLCRobot.cdx
Data/DLCRobot.esm
Data/DLCworkshop01 - Geometry.csg
Data/DLCworkshop01 - Main.ba2
Data/DLCworkshop01 - Textures.ba2
Data/DLCworkshop01.cdx
Data/DLCworkshop01.esm
Data/Fallout4 - Animations.ba2
Data/Fallout4 - Geometry.csg
Data/Fallout4 - Interface.ba2
Data/Fallout4 - Materials.ba2
Data/Fallout4 - Meshes.ba2
Data/Fallout4 - MeshesExtra.ba2
Data/Fallout4 - Misc.ba2
Data/Fallout4 - Nvflex.ba2
Data/Fallout4 - Shaders.ba2
Data/Fallout4 - Sounds.ba2
Data/Fallout4 - Startup.ba2
Data/Fallout4 - Textures1.ba2
Data/Fallout4 - Textures2.ba2
Data/Fallout4 - Textures3.ba2
Data/Fallout4 - Textures4.ba2
Data/Fallout4 - Textures5.ba2
Data/Fallout4 - Textures6.ba2
Data/Fallout4 - Textures7.ba2
Data/Fallout4 - Textures8.ba2
Data/Fallout4 - Textures9.ba2
Data/Fallout4 - Voices.ba2
Data/Fallout4.cdx
Data/Fallout4.esm
Data/ccBGSFO4001-PipBoy(Black) - Main.ba2
Data/ccBGSFO4001-PipBoy(Black) - Textures.ba2
Data/ccBGSFO4003-PipBoy(Camo01) - Main.ba2
Data/ccBGSFO4003-PipBoy(Camo01) - Textures.ba2
Data/ccBGSFO4004-PipBoy(Camo02) - Main.ba2
Data/ccBGSFO4004-PipBoy(Camo02) - Textures.ba2
Data/ccBGSFO4006-PipBoy(Chrome) - Main.ba2
Data/ccBGSFO4006-PipBoy(Chrome) - Textures.ba2
Data/ccBGSFO4016-Prey - Main.ba2
Data/ccBGSFO4016-Prey - Textures.ba2
Data/ccBGSFO4018-GaussRiflePrototype - Main.ba2
Data/ccBGSFO4018-GaussRiflePrototype - Textures.ba2
Data/ccBGSFO4019-ChineseStealthArmor - Main.ba2
Data/ccBGSFO4019-ChineseStealthArmor - Textures.ba2
Data/ccBGSFO4020-PowerArmorSkin(Black) - Main.ba2
Data/ccBGSFO4020-PowerArmorSkin(Black) - Textures.ba2
Data/ccBGSFO4038-HorseArmor - Main.ba2
Data/ccBGSFO4038-HorseArmor - Textures.ba2
Data/ccBGSFO4044-HellfirePowerArmor - Main.ba2
Data/ccBGSFO4044-HellfirePowerArmor - Textures.ba2
Data/ccFRSFO4001-HandmadeShotgun - Main.ba2
Data/ccFRSFO4001-HandmadeShotgun - Textures.ba2
Data/ccFSVFO4001-ModularMilitaryBackpack - Main.ba2
Data/ccFSVFO4001-ModularMilitaryBackpack - Textures.ba2
Data/ccFSVFO4002-MidCenturyModern - Main.ba2
Data/ccFSVFO4002-MidCenturyModern - Textures.ba2
Data/Video/
Data/Video/AGILITY.bk2
Data/Video/CHARISMA.bk2
Data/Video/ENDURANCE.bk2
Data/Video/Endgame_FEMALE_A.bk2
Data/Video/Endgame_FEMALE_B.bk2
Data/Video/Endgame_MALE_A.bk2
Data/Video/Endgame_MALE_B.bk2
Data/Video/GameIntro_V3_B.bk2
Data/Video/INTELLIGENCE.bk2
Data/Video/Intro.bk2
Data/Video/LUCK.bk2
Data/Video/MainMenuLoop.bk2
Data/Video/PERCEPTION.bk2
Data/Video/STRENGTH.bk2
Fallout4/
Fallout4/Fallout4Prefs.ini

sent 32,343,221,508 bytes  received 4,690 bytes  17,153,660.14 bytes/sec
total size is 33,828,659,462  speedup is 1.05
find: ‘/run/media/mmcblk0p1/Downloads/SteamCMD/linux32/steamapps/content/app_377160/’: No such file or directory
Fallout London installation path found.
Step 7: Manual Installation of Fallout London
Proton Experimental is installed on Internal SSD. Continue...
Fallout London installation path found.
Drive F: successfully created pointing to /run/media/mmcblk0p1/steamapps/common/Fallout 4

GoG installer for Fallout London will now launch.

1. Click Install
2. Select Drive F:
3. Click Install Here

Close the installer after it's done to continue the setup process.

wineserver: no process found
Proton: Upgrading prefix from GE-Proton7-25 to 9.0-202 (/home/deck/.steam/steam/steamapps/compatdata/377160/)
Proton: Prefix has an invalid version?! You may want to back up user files and delete this prefix.
wine: using kernel write watches, use_kernel_writewatch 2.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.
wine: using kernel write watches, use_kernel_writewatch 2.

**Comment by minimanlion** [comment]
Fix is to remove hard drive and then run script again using last known step

**Comment by krupar101** [comment]
We will make sure to address this issue in the next update.
have fun, and remember - mind the gap.
