### ISSUE TITLE
Bad Math Error after Fresh Install of New Hotfix Version

### ISSUE THREAD

**Issue by hmidd96** [overkillwtf/folon-steamdeck-installer#5]
Crash Log: https://pastebin.com/0sFinj1R
No real screenshots to add, just a standard fatal_error.

If it helps I had the same error when trying to install manually, and again after a factory reset and then again after using your tool.

Wonder if it is due to vsync.

**Comment by krupar101** [comment]
Hey there, 
I'm little bit confused. 

The logs say you are installing it on windows 10. Are you using WSL? 

Please describe the process you go through in as much detail as possible.

**Comment by hmidd96** [comment]
Not using WSL as far as I know, just factory reset the steam deck and followed the instructions on your overkill link. Maybe the crash log is just showing Windows because that's what Fallout London presumes you will use, I am just using Steam OS

**Comment by hmidd96** [comment]
Followed your process to the letter
What is weird is that it generates the exact same error as when I tried a fresh manual install the way I did it originally (which worked perfectly) 
Makes me think it’s an issue with the Fallout London latest version!

**Comment by hmidd96** [comment]
Only other info I have is that I have done a trawl of the fallout London discord and it doesn’t seem to be a unique issue, also seems to be affecting Linux users more, no matter the method of install. No solution on the discord yet either

**Comment by loganbestwick** [comment]
Just installed an hour ago and am having the same issue. Crashes on startup.

**Comment by krupar101** [comment]
Please provide the Konsole output you get when the script fails.

**Comment by hmidd96** [comment]
For me the script runs perfectly
It only crashes on game start up

**Comment by krupar101** [comment]
Can you try to change the proton version to proton GE 9-10 or higher?

You can use the ProtonUp-QT app to download if you haven't done that in the past.

**Comment by hmidd96** [comment]
I managed to get it working via:
“Go to "/home/deck/.steam/steam/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/Documents/My Games/Fallout4" and make sure only 2 files are inside. folder called "F4SE" and Fallout4.INI”

For me there was an additional ini file “Fallout4Prefs.ini”, that stopped it working for some odd reason

**Comment by krupar101** [comment]
Interesting, the script already removes this file after you close the GoG launcher in next steps. Maybe you didn’t run it till the end? 

Anyway. Issue closed :)
