### ISSUE TITLE
Wouldn't run at all without a reboot.

### ISSUE THREAD

**Issue by twizzlebizzle** [overkillwtf/folon-steamdeck-installer#6]
I know this might seems obvious but I couldn't get the mod to run when launching fallout 4 without a reboot of the steamdeck.  
It stumped me for a while, maybe add it to the guide?

Without a reboot it just sat on the steam logo after launching fallout 4.

**Comment by krupar101** [comment]
We added the information to the guide :)
Thanks for the message. 

https://overkill.wtf/fallout-london-steam-deck-1-click-installer/

Closing the issue.
