### ISSUE TITLE
Install broke my konsole sfter failing install

### ISSUE THREAD

**Issue by bball3212** [overkillwtf/folon-steamdeck-installer#7]
I'm not sure I can give output on issue since I can't open konsole anymore. I picked system instead of user when the option came up and then it failed on download of stuff and I can't open konsole anymore
It was like this error 

![Screenshot_20240810_185327_Reddit](https://github.com/user-attachments/assets/ff20204e-2f07-4745-8b5c-40a7a4c6ca03)

Any ideas?

**Comment by krupar101** [comment]
Try rebooting the steam deck if Konsole does not open. Failing depot downloads coud be caused by unstable internet connection or not enough memory to download the files.

**Comment by krupar101** [comment]
This is the excerpt from official [Fallout London page](https://fallout4london.com/release/)

To download the content for each of the DLCs that you may own type these commands
(having those DLCs is necessary to play Fallout: London):

For Automatron use:
download_depot 377160 435870 1691678129192680960

For Automatron English language pack use:
download_depot 377160 435871 5106118861901111234

For Wasteland Workshop use:
download_depot 377160 435880 1255562923187931216

For Far Harbor use:
download_depot 377160 435881 1207717296920736193

Far Harbor English language pack use:
download_depot 377160 435882 8482181819175811242

For Contraptions Workshop use:
download_depot 377160 480630 5527412439359349504

For Vault-Tec Workshop use:
download_depot 377160 480631 6588493486198824788

For Vault-Tec Workshop English language pack use:
download_depot 377160 393885 5000262035721758737

For Nuka World use:
download_depot 377160 490650 4873048792354485093

For Nuka World English language pack use:
download_depot 377160 393895 7677765994120765493

This should help you recognize which depot is failing and which DLC it is referring to.

**Comment by bball3212** [comment]
Hey thanks for the info, I did try that and after various times it still
just opens and closes immediately.  I'm afraid I'll have to redo the OS but
was trying to avoid
