### ISSUE TITLE
Missing licenses/depot fail

### ISSUE THREAD

**Issue by tscales21** [overkillwtf/folon-steamdeck-installer#8]
I am currently on Step 3 of installing Fallout London on the Steam Deck making sure I followed all of the prerequisites such as double checking installed files in gaming mode, double checking if all DLC was installed and not having High Resolution, and double checking that Proton Experimental was installed. Next, I created new accounts for Nexus Mods and GOG. After installing Fallout London from the GOG Website and restarting Heroic, I began Step 2 and entered Konsole. 

I entered my Steam login credentials and was asked to enter a two-factor code. I entered the Steam Guard code given from the Steam Mobile app and afterwards I got an "OK" message later telling that download depots failed with missing licenses messages and telling me to run the script again. 

What could I be missing? If you need pictures I can run the process and show.

**Comment by krupar101** [comment]
Missing licenses means that you have not purchased some of the Fallout 4 DLC's. The process requires you to have all DLC's or Fallout 4 GOTY edition. 

This is the excerpt from official [Fallout London page](https://fallout4london.com/release/) 

For Automatron use:
download_depot 377160 435870 1691678129192680960

For Automatron English language pack use:
download_depot 377160 435871 5106118861901111234

For Wasteland Workshop use:
download_depot 377160 435880 1255562923187931216

For Far Harbor use:
download_depot 377160 435881 1207717296920736193

Far Harbor English language pack use:
download_depot 377160 435882 8482181819175811242

For Contraptions Workshop use:
download_depot 377160 480630 5527412439359349504

For Vault-Tec Workshop use:
download_depot 377160 480631 6588493486198824788

For Vault-Tec Workshop English language pack use:
download_depot 377160 393885 5000262035721758737

For Nuka World use:
download_depot 377160 490650 4873048792354485093

For Nuka World English language pack use:
download_depot 377160 393895 7677765994120765493

This should help you recognize which depot is failing and which DLC it is referring to.

**Comment by tscales21** [comment]
I have all the DLC installed on the Steam version. I double checked in Properties in Gaming mode and in game which says that all DLC is installed. I go into Konsole and it still is telling me the missing licenses. I even restarted my whole Steam Deck and it still didn't work. 

I purchased all of the DLC on the Steam website directly from here:

https://store.steampowered.com/sub/199943/

**Comment by krupar101** [comment]
Please share a screenshot of all your DLC's

You should have those installed:
![image](https://github.com/user-attachments/assets/38effdef-7700-46e2-b638-27b8c23313f2)

**Comment by tscales21** [comment]
Here's the screenshots...
![image](https://github.com/user-attachments/assets/a2941781-0434-4ff2-8e76-6ba91a58deaf)

![image](https://github.com/user-attachments/assets/e9ff5ee9-fd34-4a5e-bd7b-932db0585b04)

![image](https://github.com/user-attachments/assets/74c3ab8a-057e-4268-b9e7-0edea8a2f39a)

I took 3 of them but let me know if you need any more screenshots from me.

**Comment by krupar101** [comment]
Basically looks like the problem is with your licenses to the DLC's 

Maybe you are logging into an account where the DLC is not purchased
Are you using Family Sharing?

**Comment by krupar101** [comment]
Problem solved.
Solution: In the script provide credentials to an account on which you own Fallout 4 GOTY or Fallout 4 with all DLC.

**Comment by mueslimak3r** [comment]
I'm having this issue too. @tscales21 did you find a solution?
I specifically purchased the GOTY edition on steam, and confirmed that I own all of the DLC required by the mod.
I'll post a solution if I find it.

**Comment by krupar101** [comment]
@mueslimak3r 
This is a known problem. Please check the troubleshooting PDF published on overkill website. 

https://overkill.wtf/content/files/2024/10/Ultimate-Fallout-London-Guide-for-Steam-Deck-and-Linux.pdf

You can find a section named "Solving Depot download failed error during downgrade" on page 60 and 61.

**Comment by mueslimak3r** [comment]
I appreciate your quick response. Unfortunately the solution doesn't seem to be simply 1) not owning the game/DLC 2) not truly owning the game 3) incorrect creds.

I have checked both the ownership of the game/DLC, and my login creds.
The logs show `OK` after login
The first package I get access denied for is `5847529232406005096`, which looks like the exe for the downgraded version of the base game, which I confirmed I own.

I will test manually grabbing these packages using SteamCMD on a different machine and report back.

**Comment by krupar101** [comment]
> I appreciate your quick response. Unfortunately the solution doesn't seem to be simply 1) not owning the game/DLC 2) not truly owning the game 3) incorrect creds.
> 
> I have checked both the ownership of the game/DLC, and my login creds. The logs show `OK` after login The first package I get access denied for is `5847529232406005096`, which looks like the exe for the downgraded version of the base game, which I confirmed I own.
> 
> I will test manually grabbing these packages using SteamCMD on a different machine and report back.

You are correct, this depot specifically is the Fallout4.exe file.
https://steamdb.info/depot/377162/

Please try to download it manually and check if you get the same error. 

The downgrade list we use is the same as the official one from Fallout London Downgrader: 
https://github.com/Fallout-London/FOLON-FO4Downgrader/blob/main/WindowsDowngrader.py

![Image](https://github.com/user-attachments/assets/1eff9897-3bdd-4352-b6dd-1082b5c32971)

https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/download/BackendFiles/DepotsList.txt

Also if you own the game there should be no reason for you not to have access. Sometimes if you try to download too many times in a row SteamCMD downloads become Rate Limited and it does not allow you to download anything for ~60 minutes. 

Also the best way to confirm that you put in the correct credentials is to login to the steam website. 
https://store.steampowered.com/

Open a new browser tab in incognito and try to log in. I know it seems like a stupid test but it actually solved this issue for many people in the past.

**Comment by krupar101** [comment]
@mueslimak3r 
Did you have time to check the manual SteamCMD download method? 
I am curious about the results.

**Comment by mueslimak3r** [comment]
I can download these packages just fine using SteamCMD on macos. I just installed it from `brew` and ran each line individually. I'll SSH into my steam deck and try the same using the flatpak of SteamCMD
https://github.com/overkillwtf/folon-steamdeck-installer/blob/bb86128c344c923686f6199e327af25f4d40a46c/fallout.sh#L383-L396

**Comment by mueslimak3r** [comment]
I got it working, had to close Steam first (it auto launches in desktop mode). Only one login is allowed at a time when downloading old versions of games.
https://steamdb.info/blog/manifest-request-codes/

Opened a PR to update the README
