### ISSUE TITLE
SteamDeck: Not able to access the Fallout 4 Launcher to change graphical settings.

### ISSUE THREAD

**Issue by BJZ3k** [overkillwtf/folon-steamdeck-installer#9]
Following the instructions installs the mod perfectly with no error. The one issue I have is that I believe the graphical settings auto set so my FPS drops to as low as 15 in the open world. When I first launched the game after the mod installed I was never given the chance to set my graphic settings through the launcher. So I looked around for ways to access the launcher and none of the answers I found work. I tried adding SteamDeck=0 %command% on Preferences then Startup but all this does is just start the game normally I get no launcher. I then tried adding Fallout4Launcher.exe to steam and launching it from there but it crashes back out instantly. I also tried changing Fallout4Launcher.exe.old with out the old wording and launching that with out any success. It insta crashes as well. Is there a way to access the launcher?? I have searched for hours and tried everything with no success. I would appreciate any insight or help. Much thanks.

**Comment by krupar101** [comment]
Here is what you can try:
1. Find fallout 4 in your Steam Library
2. Right-click on it and select Properties
3. Go to Installed Files -> View files
4. a folder will open and show your Fallout 4 Installation Directory.
5. In that directory you will see those 2 files: fallout4launcher.exe and fallout4launcher.exe.old
6. Rename the fallout4launcher.exe to fallout4launcher.exe.f4se
7. Rename fallout4launcher.exe.old to fallout4launcher.exe

Run the game - launcher should open -> change the settings there. 

Then to make fallout london work again:
1. Rename the fallout4launcher.exe to fallout4launcher.exe.old
2. Rename fallout4launcher.exe.f4se to fallout4launcher.exe

**Comment by colourlimited** [comment]
> Here is what you can try:
> 
> 1. Find fallout 4 in your Steam Library
> 2. Right-click on it and select Properties
> 3. Go to Installed Files -> View files
> 4. a folder will open and show your Fallout 4 Installation Directory.
> 5. In that directory you will see those 2 files: fallout4launcher.exe and fallout4launcher.exe.old
> 6. Rename the fallout4launcher.exe to fallout4launcher.exe.f4se
> 7. Rename fallout4launcher.exe.old to fallout4launcher.exe
> 
> Run the game - launcher should open -> change the settings there.
> 
> Then to make fallout london work again:
> 
> 1. Rename the fallout4launcher.exe to fallout4launcher.exe.old
> 2. Rename fallout4launcher.exe.f4se to fallout4launcher.exe

this worked for me.
thank you for the script and fix.

**Comment by krupar101** [comment]
Closing the issue:
Solution: 

Find fallout 4 in your Steam Library
Right-click on it and select Properties
Go to Installed Files -> View files
a folder will open and show your Fallout 4 Installation Directory.
In that directory you will see those 2 files: fallout4launcher.exe and fallout4launcher.exe.old
Rename the fallout4launcher.exe to fallout4launcher.exe.f4se
Rename fallout4launcher.exe.old to fallout4launcher.exe
Run the game - launcher should open -> change the settings there.

Then to make fallout london work again:

Rename the fallout4launcher.exe to fallout4launcher.exe.old
Rename fallout4launcher.exe.f4se to fallout4launcher.exe
